name: Build project
on: [push]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build app
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Test app
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
      - name: Deploy app
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: 2ff2f5ab-e4fb-4f99-9895-d23d7506d8cf
          heroku_app_name: rocket-web-server
          heroku_email: wh75er@gmail.com
          buildpack: "https://github.com/emk/heroku-buildpack-rust.git"
        env:
          HD_DATABASE_URL: postgres://vukyhmpxfnjwxk:5ad58b1b4b9a869a2d6f814a6aa1980116d8632bad2eb5614ce1aba26a7f293b@ec2-54-75-150-32.eu-west-1.compute.amazonaws.com:5432/d4vh8mhcdji0en
          HD_ROCKET_DATABASES: '{pgdb={url="postgres://vukyhmpxfnjwxk:5ad58b1b4b9a869a2d6f814a6aa1980116d8632bad2eb5614ce1aba26a7f293b@ec2-54-75-150-32.eu-west-1.compute.amazonaws.com:5432/d4vh8mhcdji0en"}}'
      - name: Checkout test repository
        uses: actions/checkout@v2
        with:
          repository: Romanow/person-service-test
          path: integration-tests
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run integration tests
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: integration-tests
          wrapper-directory: integration-tests
          arguments: clean test -PtargetUrl=https://rocket-web-server.herokuapp.com/
