name: Build project
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build app
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Test app
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
      - name: Deploy app
        uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: rocket-web-server
          heroku_email: wh75er@gmail.com
          buildpack: "https://github.com/emk/heroku-buildpack-rust.git"
        env:
          HD_DATABASE_URL: ${{secrets.HEROKU_DB_ADDRESS}}
          HD_ROCKET_DATABASES: '{pgdb={url="${{secrets.HEROKU_DB_ADDRESS}}"}}'
          HD_HEROKU_APP_NAME: rocket-web-server
      - name: Checkout test repository
        uses: actions/checkout@v2
        with:
          repository: Romanow/person-service-test
          path: integration-tests
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run integration tests
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: integration-tests
          wrapper-directory: integration-tests
          arguments: clean test -PtargetUrl=https://rsoi-person-service.herokuapp.com
